// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsiztgafaapqtyvoqkln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzaXp0Z2FmYWFwcXR5dm9xa2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMzkxOTksImV4cCI6MjA3MDcxNTE5OX0.1PWo0YP_DMehhV-a-XZGPvI_ab9bvBqSUeI719y-6Yc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});